### ISSUE TITLE
Please enable/update this package for CakePHP 4

### ISSUE THREAD

**Issue by MuhammadSulman** [robotusers/cakephp-chunk#2]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/23367323/204090173-cfc8f098-160f-4282-82c3-d4b159fde620.png">

**Comment by robertpustulka** [comment]
@MuhammadSulman I no longer use this package in my projects. Feel free to post a PR and I'd be happy to merge

**Comment by ravage84** [comment]
@robertpustulka thank you for  creating this plugin. Lovely stuff. Something like this is currently certainly missing from the framework.

I tested your https://github.com/robotusers/cakephp-chunk/tree/0.2 branch and it seems to be working just fine.

What was the reason to a) not release it in the current state for CakePHP 4.x and b) abandon the package in your projects?

At my employer, we have a use case for your plugin but I also think the greater CakePHP community could benefit from it.

Would you be willing to transfer this plugin to some other GH organisation?
Alternatively, would you be fine if we integrated the code into the framework itself?

**Comment by robertpustulka** [comment]
@ravage84 thanks :)

I probably forgot to make a release. Now I'm remembering I'm using this plugin in one of my Cake 4 apps.

The reason I'm not using it is just because it's a wrapper for limit/page which is sometimes more straightforward to use.

I'll merge 0.2 branch and make a release
